tasks:
  - id: Startup
    normal:
      - func: Log
        args:
          msg: log 1
          stdout: true
      - func: Log
        args:
          msg: log 2
    error:
      - func: Log
        args:
          msg: Error !
    final:
      - func: Log
        args:
          msg: Finall func
  - id: Hoge
    normal:
      - func: Log
        args:
          msg: log 3
      - func: Log
        args:
          msg: log 4

