tasks:
  - id: Init
    normal:
      - func: Log
        args:
          msg: Initial func 0
      - func: Log
        args:
          msg: |-
            Long long message.
            new line.

  - id: Startup
    normal:
      - func: SetStore
        args:
          sets:
            - key: stdout
              val: true
      - func: Copy
        args:
          pairs:
            - src: ${_CMD_DIR}
              dst: ${_CFG_DIR}/_test/binfiles
              filter:
                matches: [e$]
                ignores: [\/g]
              recurse: true
          async: copy
      - func: Exec
        args:
          cmds:
            - cmd: ls
              arg: -la
              results:
                - code: 0
                  id: Ok
              other:
                id: Ng
      - func: Run
        args:
          targets:
            - id: Hoge
            - id: Fuga
              file: _test/fuga.yml
      - func: Exec
        args:
          cmds:
            - cmd: lsls
              results:
                - code: 0
              other:
                id: Ng
      - func: Exec
        args:
          cmds:
            - cmd: gsr
              arg: --status --ahead --behind
      - func: Log
        args:
          msg: "log 1 ${@date(2006-01-02 15:04)}"
          stdout: ${stdout}
      - func: Log
        args:
          msg: log 2
    error:
      - func: Log
        args:
          msg: Error !
    final:
      - func: Log
        args:
          msg: Finall func

  - id: Hoge
    normal:
      - func: Log
        args:
          msg: log 3
      - func: Log
        args:
          msg: log 4

  - id: Ok
    normal:
      - func: Log
        args:
          msg: Ok error nothing.

  - id: Ng
    normal:
      - func: Log
        args:
          msg: Ng error occur.

log:
  level: info
  output: true
  encoding: console
  encoderConfig:
    messageKey: Msg
    levelKey: Level
    timeKey: Time
    nameKey: Name
    callerKey: Caller
    stacktraceKey: St
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: string
    callerEncoder: short
  outputPaths:
    - ${_CFG_DIR}/${_CFG_NAME}_${@date(2006-01-02-15-04-05.000)}.log
  errorOutputPaths:
    - stderr

