tasks:
  - id: Init
    normal:
      - func: Log
        args:
          msg: Initial func 0
      - func: Log
        args:
          msg: |-
            Long long message.
            new line.

  - id: Startup
    normal:
      - func: SetStore
        args:
          sets:
            - key: stdout
              val: true
      - func: Log
        args:
          msg: log 1 ${@date(2006-01-02 15:04)}
          stdout: ${stdout}
      - func: Log
        args:
          msg: log 2
      - func: Run
        args:
          targets:
            - id: Hoge
            - id: Fuga
              file: _test/fuga.yml
    error:
      - func: Log
        args:
          msg: Error !
    final:
      - func: Log
        args:
          msg: Finall func

  - id: Hoge
    normal:
      - func: Log
        args:
          msg: log 3
      - func: Log
        args:
          msg: log 4

log:
  level: debug
  encoding: console
  encoderConfig:
    messageKey: Msg
    levelKey: Level
    timeKey: Time
    nameKey: Name
    callerKey: Caller
    stacktraceKey: St
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: string
    callerEncoder: short
  outputPaths:
    - ${_CFG_DIR}/${_CFG_NAME}_${@date(20060102150405)}.log
    - stdout
  errorOutputPaths:
    - stderr

